services:
  - type: web
    name: coffee-shop-api
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: coffee-shop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@coffee.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

databases:
  - name: coffee-shop-db
    plan: free
